### PR TITLE
Update Vagrantfile

### PR DESCRIPTION
**Pull request by JohnsonMikeJ**

### CODE REVIEW

**Comment by marcindulak** [comment]
I assume 'centos/7' is up-to-date?

    $ vagrant box list | grep 'centos/7'

Do all your Virtualbox VM's lack 'IDE Controller'? 

    $ for vm in `vboxmanage list runningvms | cut -d' ' -f2`; do vboxmanage showvminfo $vm | grep 'Storage Controller Name'; done
    $ grep 'StorageController name'  ~/.vagrant.d/boxes/*/*/virtualbox/box.ovf

**Comment by JohnsonMikeJ** [comment]
[~]$  vagrant box list | grep 'centos/7'
centos/7 (virtualbox, 1610.01)
[~]$ for vm in `vboxmanage list runningvms | cut -d' ' -f2`; do vboxmanage showvminfo $vm | grep 'Storage Controller Name'; done
Storage Controller Name (0):            IDE
Storage Controller Name (0):            IDE
Storage Controller Name (0):            IDE
Storage Controller Name (0):            IDE

[~]$ grep 'StorageController name'  ~/.vagrant.d/boxes/*/*/virtualbox/box.ovf

[~]

**Comment by marcindulak** [comment]
I see 'IDE Controller' is defined in `centos/7` 1610.01:

    $ wget https://atlas.hashicorp.com/centos/boxes/7/versions/1610.01/providers/virtualbox.box
    $ tar xvOf virtualbox.box box.ovf | xmllint --format - | grep StorageController
    ...
    <ns0:StorageController Bootable="true" PortCount="2" name="IDE Controller" type="PIIX4" useHostIOCache="true">
    ....

Do the box.ovf files installed under `~/.vagrant.d` have a mention of 'IDE Controller'?
 
    $ xmllint --format ~/.vagrant.d/boxes/centos-VAGRANTSLASH-7/1610.01/virtualbox/box.ovf  | grep 'StorageController'

Is the 'IDE Controller' missing only on 'centos/7', what about puppetlabs?

    $ BOX='centos/7' vagrant up
    $ vagrant destroy -f
    $ BOX='puppetlabs/centos-7.2-64-puppet' vagrant up

with the following:

    # -*- mode: ruby -*-
    # vi: set ft=ruby :

    Vagrant.configure(2) do |config|
      config.vm.define "ideControllerProblem" do |machine|
        machine.vm.box = ENV.fetch('BOX', 'centos/7')
        machine.vm.box_url = machine.vm.box
        machine.vm.provider "virtualbox" do |v|
          v.memory = 256
          v.cpus = 1
          disk = 'sdb.vdi'
          if !File.exist?(disk)
            v.customize ['createhd', '--filename', disk, '--size', 64, '--variant', 'Fixed']
            v.customize ['modifyhd', disk, '--type', 'writethrough']
          end
          v.customize ['storageattach', :id, '--storagectl', 'IDE Controller', '--port', 0, '--device', 1, '--type', 'hdd', '--medium', disk]
        end
      end
      config.vm.define "ideControllerProblem" do |machine|
        machine.vm.provision :shell, :inline => "hostname ideControllerProblem", run: "always"
      end
    end

Can you also paste the exact error you are getting from 'centos/7' and 'IDE Controller' using the above Vagrantfile?

**Comment by JohnsonMikeJ** [comment]
```bash
A customization command failed:

["storageattach", :id, "--storagectl", "IDE Controller", "--port", 0, "--device", 1, "--type", "hdd", "--medium", "sdb.vdi"]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["storageattach", "70c40f3d-f6ad-404e-bfb7-2f420ab36c9f", "--storagectl", "IDE Controller", "--port", "0", "--device", "1", "--type", "hdd", "--medium", "sdb.vdi"]

Stderr: VBoxManage: error: Could not find a controller named 'IDE Controller'
>

Please fix this customization and try again.
```

**Comment by marcindulak** [comment]
What about:

    $ xmllint --format ~/.vagrant.d/boxes/centos-VAGRANTSLASH-7/1610.01/virtualbox/box.ovf  | grep 'StorageController'

Does puppetlabs box fail too?

    $ BOX='puppetlabs/centos-7.2-64-puppet' vagrant up

**Comment by JohnsonMikeJ** [comment]
```bash
[~]$ xmllint --format ~/.vagrant.d/boxes/centos-VAGRANTSLASH-7/1610.01/virtualbox/box.ovf  | grep 'StorageController'

      <ns0:StorageControllers>
        <ns0:StorageController Bootable="true" PortCount="2" name="IDE Controller" type="PIIX4" useHostIOCache="true">
        </ns0:StorageController>
      </ns0:StorageControllers>
```

puppetlabs box started just fine (once I remembered to destroy the CentOS/7 test)

**Comment by JohnsonMikeJ** [comment]
```bash
$ for vm in `vboxmanage list runningvms | cut -d' ' -f2`; do vboxmanage showvminfo $vm | grep 'Name'; done
Name:            vagrant-mariadb-galera-tutorial-centos7_node0_1480787107111_53377
Storage Controller Name (0):            IDE
Name:            vagrant-mariadb-galera-tutorial-centos7_node1_1480787377950_59875
Storage Controller Name (0):            IDE
Name:            vagrant-mariadb-galera-tutorial-centos7_node2_1480787552725_82467
Storage Controller Name (0):            IDE
Name:            vagtest_ideControllerProblem_1480787571237_86868
Storage Controller Name (0):            IDE Controller
Name: 'vagrant', Host path: '/Users/mjohnson/Development/vagtest' (machine mapping), writable
Name:            vagrant-mariadb-galera-tutorial-centos7_client0_1480787736218_40736
Storage Controller Name (0):            IDE
```

**Comment by marcindulak** [comment]
Can you also try:

    $ BOX='bento/centos-7.2' vagrant up

Then by adding the `VERSION` variable you could verify if the oldest 'centos/7' box fails too:

    $ VERSION='1505.01' vagrant up

but this time with the modified Vagrantfile.

    # -*- mode: ruby -*-
    # vi: set ft=ruby :

    Vagrant.configure(2) do |config|
      config.vm.define "ideControllerProblem" do |machine|
        machine.vm.box = ENV.fetch('BOX', 'centos/7')
        machine.vm.box_url = machine.vm.box
        machine.vm.box_version = ENV.fetch('VERSION', '1610.01')
        machine.vm.provider "virtualbox" do |v|
          v.memory = 256
          v.cpus = 1
          disk = 'sdb.vdi'
          if !File.exist?(disk)
            v.customize ['createhd', '--filename', disk, '--size', 64, '--variant', 'Fixed']
            v.customize ['modifyhd', disk, '--type', 'writethrough']
          end
          v.customize ['storageattach', :id, '--storagectl', 'IDE Controller', '--port', 0, '--device', 1, '--type', 'hdd', '--medium', disk]
        end
      end
      config.vm.define "ideControllerProblem" do |machine|
         machine.vm.provision :shell, :inline => "hostname ideControllerProblem", run: "always"
      end
    end

We will need to send this Vagranfile to https://lists.centos.org/mailman/listinfo/centos-devel asking if anybody else is seeing this problem.
Do you want to send it or should I do it?

**Comment by JohnsonMikeJ** [comment]
```bash
mjohnson@MacBook-Pro$ VERSION='1505.01' vagrant up
Bringing machine 'ideControllerProblem' up with 'virtualbox' provider...
==> ideControllerProblem: Box 'centos/7' could not be found. Attempting to find and install...
    ideControllerProblem: Box Provider: virtualbox
    ideControllerProblem: Box Version: 1505.01
==> ideControllerProblem: Loading metadata for box 'centos/7'
    ideControllerProblem: URL: https://atlas.hashicorp.com/centos/7
==> ideControllerProblem: Adding box 'centos/7' (v1505.01) for provider: virtualbox
    ideControllerProblem: Downloading: https://atlas.hashicorp.com/centos/boxes/7/versions/1505.01/providers/virtualbox.box
==> ideControllerProblem: Successfully added box 'centos/7' (v1505.01) for 'virtualbox'!
==> ideControllerProblem: Importing base box 'centos/7'...
==> ideControllerProblem: Matching MAC address for NAT networking...
==> ideControllerProblem: Checking if box 'centos/7' is up to date...
==> ideControllerProblem: Setting the name of the VM: vagtest_ideControllerProblem_1480791273938_36073
==> ideControllerProblem: Fixed port collision for 22 => 2222. Now on port 2203.
==> ideControllerProblem: Clearing any previously set network interfaces...
==> ideControllerProblem: Preparing network interfaces based on configuration...
    ideControllerProblem: Adapter 1: nat
==> ideControllerProblem: Forwarding ports...
    ideControllerProblem: 22 (guest) => 2203 (host) (adapter 1)
==> ideControllerProblem: Running 'pre-boot' VM customizations...
A customization command failed:

["storageattach", :id, "--storagectl", "IDE Controller", "--port", 0, "--device", 1, "--type", "hdd", "--medium", "sdb.vdi"]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["storageattach", "51e7f61f-2d6f-43dc-916b-1d8dad0ea505", "--storagectl", "IDE Controller", "--port", "0", "--device", "1", "--type", "hdd", "--medium", "sdb.vdi"]

Stderr: VBoxManage: error: Could not find a controller named 'IDE Controller'
>

Please fix this customization and try again.
```
I actually found a couple other references to this issue that present changing the storage controller to "IDE" as a workaround so it may already be a know issue. 

Feel free to submit the issue as you see fit.

Thanks,

-M

**Comment by marcindulak** [comment]
Reported at https://lists.centos.org/pipermail/centos-devel/2016-December/015433.html

**Comment by JohnsonMikeJ** [comment]
Awesome thanks!

**Comment by marcindulak** [comment]
I've attached a modified box.ovf on https://lists.centos.org/pipermail/centos-devel/2016-December/015435.html. Could you try to copy it over `~/.vagrant.d/boxes/centos-VAGRANTSLASH-7/1610.01/virtualbox/` and try if this makes 'IDE Controller' available?

**Comment by JohnsonMikeJ** [comment]
I've been busy the last week and forgot where I left off so I just rm -fr'd it, reverted the Vagrant file and it came up error free so someone must have fixed the box ;)

**Comment by marcindulak** [comment]
There has been no version of 'centos/7'  after 1610.01 - the problem is still there, at least for me with
Vagrant 1.9.0 VBox 5.1.10r112026

**Comment by JohnsonMikeJ** [comment]
So you are right. I must have grabbed your modified box.ovf and forgot :/ So apparently that enabled "IDE Controller".

**Comment by marcindulak** [comment]
Issue submitted also at https://github.com/redhat-imaging/imagefactory/issues/393

**Pull request closed without merging**
